#ifndef SERIAL_LOG_H
#define SERIAL_LOG_H

#include <stdint.h>

/* UART0 TX on PA10, 115200 8N1. Hardware setup is generated by empty.syscfg. */
void serial_log_init(void);

/* Call once per fixed 5 ms control tick. This only builds and queues text. */
void serial_log_task(uint32_t now_tick);

/* Call repeatedly from the main-loop idle path. This fills the UART TX FIFO. */
void serial_log_service(void);

uint32_t serial_log_get_dropped_message_count(void);
uint16_t serial_log_get_queued_byte_count(void);

#endif
